absinthe-graphql/dataloader

lib/dataloader.ex
lib/dataloader/ecto.ex
lib/dataloader/kv.ex
lib/dataloader/source.ex
test/dataloader/ecto_test.exs

Ecto Caching

---

lib/dataloader/ecto.ex
priv/test_repo/migrations/1_migrate_all.exs
test/dataloader/ecto/custom_batch_test.exs
test/dataloader/ecto_test.exs
test/support/like.ex
test/support/post.ex

Fixes #5 
This PR adds the ability to configure customizable batch loading functions to the Ecto data source. The `query` option already made it possible to add scoping conditions when looking up data. What was lacking however was the ability to accumulate values, and then supply a function that could use those values to run arbitrary SQL to do the lookup.
This PR also adds support for `through` associations.
Remaining:

[WIP] Ecto batch fun

---

.gitignore
lib/dataloader/kv.ex

Use a MapSet for keys, to keep it consistent with Dataloader.Ecto, and to allow regression testing of a bug in absinthe without needing to use Dataloader.Ecto

MapSet for keys in Dataloader.KV

---

lib/dataloader/ecto.ex

Dialyzer is failing on my project with a `Function dataloader/0 has no local return`
```elixir
def dataloader() do
source = Dataloader.Ecto.new(Repo, query: &query/2, run_batch: &run_batch/5)
Dataloader.new()
|> Dataloader.add_source(:source, source)
end
```
I _think_ this is because we are missing a type on the `Dataloader.Ecto.new/2` function, because when I remove `run_batch` it passes...
I looked at using `batch_fun` for the type, but that wasn't the right number of params by the look of it, so I went with the simple `fun`

Adds a type for the run_batch option on Dataloader.Ecto.new/2

---

lib/dataloader.ex
lib/dataloader/ecto.ex
lib/dataloader/kv.ex
lib/dataloader/source.ex

Without this, it's easy for people to configure a large timeout on a
source and not realise that the supervising process has killed it
prematurely by exiting on a default 15_000 timeout.
Note that this throws away the concept of setting a timeout on the
`Dataloader` level. I initially implemented this allowing the timeout
to be set, but this ultimately makes no sense. The only consequence of
allowing people to set a lower timeout on the `Dataloader` than exists
on their `Source` is to open ourselves up to a whole new class of bugs,
there is no benefit to doing this. So just don't allow it :).
**NOTE**: This relates directly to the bug raised in https://github.com/absinthe-graphql/dataloader/pull/35 - with this, I would never have hit that issue

Change default dataloader timeout to be the max of its sources

---

lib/dataloader.ex
lib/dataloader/ecto.ex
lib/dataloader/kv.ex
lib/dataloader/source.ex
test/dataloader/ecto_test.exs
test/dataloader/kv_test.exs
test/dataloader_test.exs

I'm raising this following an initial PR (https://github.com/absinthe-graphql/dataloader/pull/39) a couple of weeks ago. I've had a couple of other guys take a look internally before raising and so hopefully it should pretty much be there :crossed_fingers:. I ended up implementing all three ways mentioned in #39  (as this was trivial in the end; see the `do_get/2` method). Happy to make changes, rename stuff etc if you want :smile:!
Previously, if any errors occurred when a source tried to load data,
this would get logged and a `nil` would get returned.
The danger of this is that this means errors may go unnoticed in
production environments (e.g. timeouts to third parties) as a `nil`
result may be a reasonable one depending on the `Source` and data.
This provides two additional …

Add error handling when sources fail to load data

---

lib/dataloader/ecto.ex
test/dataloader/ecto_test.exs

This branch demonstrates that dataloader doesn't coerce strings to ints the way ecto does for id columns.

Demonstrate issue with strings

---

.tool-versions
lib/dataloader.ex
lib/dataloader/ecto.ex

We found when querying for lots of data that the RAM would increase
unbounded because the spawned supervisors were never shut down. This meant, even if we paginated the queries, the RAM usage
would steadily increase, until the whole request had finished.
Should close #47

Fixes memory issue when querying large amounts of data.

---

lib/dataloader.ex

This is following the merge of #48 which changed the arity of this function from `/4` to `/3`

Fix doctests broken due to removal of task supervisors

---

mix.exs

Added the source url in mix.exs so that the generated docs link to the sourcefiles.

Add source url in mix.exs

---

lib/dataloader/ecto.ex
priv/test_repo/migrations/1_migrate_all.exs
test/dataloader/ecto_test.exs
test/support/leaderboard.ex
test/support/score.ex
test/support/user.ex

Patch to address #55 based on PR #58 by @gbxl

Fix loading for nested through associations

---

lib/dataloader/ecto.ex

Somewhat frequently there are questions on Slack surrounding batch_run in dataloader. I've added some docs regarding what I use batch_run for frequently, namely doing stuff like `post_count`, `comment_count` etc. 
I might also add some docs regarding dataloader and batch_run in the Absinthe repo.

Add docs for batch_run/5

---

CHANGELOG.md
mix.exs

ecto_sql is still used for tests
Fixes #67

Switch back to depending on ecto instead of ecto_sql

---

lib/dataloader/ecto.ex
lib/dataloader/kv.ex
test/dataloader/ecto_test.exs
test/dataloader/kv_test.exs

Fixes issue #74.
`Map.get/2` will either return some `value()` or `nil`.
https://github.com/absinthe-graphql/dataloader/blob/56f7cb4ceb822f6d75c53188902b32a4cb9b737c/lib/dataloader/kv.ex#L85-L88
The above `case` statement does not specifically handle `nil`, because it (incorrectly) expects to find either an `:error` 2-tuple or a cached result.
However, when `fetch/3` is called by `load/3`, it is possible that:
1. `results` is a non-empty map, and
2.  there is no `results` entry matching `id`
In that case, `Map.get/2` would return `nil`, but it was being pattern-matched as a _positive result_ instead of an error, which caused the incorrect path to be followed in:
https://github.com/absinthe-graphql/dataloader/blob/56f7cb4ceb822f6d75c53188902b32a4cb9b737c/lib/dataloader/kv.ex#L72-L80
This …

Dataloader.KV: load new items when results are non-empty

---

lib/dataloader/ecto.ex

https://github.com/absinthe-graphql/dataloader/commit/ce9ac3f3e4649dd15a3094ad50ba841511455d31#diff-cb130db1770f44aedd393088b4d91bcdR278
This commit changed the code to use tuples, but forgot to update the Map.update logic.
Without this change, code would fail with "expected a map, got {:ok, map}".

Fix updating Dataloader.Ecto.put/4

---

lib/dataloader/ecto.ex

use backticks for atom in documentation (as the rest is using it)

Update ecto.ex docs

---

lib/dataloader.ex
lib/dataloader/ecto.ex
lib/dataloader/kv.ex
test/dataloader/ecto_test.exs
test/dataloader_test.exs

Some minor improvements to the docs and error messages.

Minor doc improvements

---

guides/telemetry.md

I believe that the event got changed part way through the PR but the guide wasn't updated to reflect the change
(this replaces #99 because I'm editing in the Github GUI and couldn't see a way to edit the file in my existing PR)

Update events in telemetry guide

---

lib/dataloader/ecto.ex
test/dataloader/ecto/limit_query_test.exs

Relates to #97 
Ecto doesn't allow preloads in subqueries, so this PR moves any preloads out to a call to `Repo.preload`.
This should support basic keyword preloads, but join preloads are dropped.
It also avoids using a lateral join when loading rows by primary key with a limit, as in the example in #97.

Avoid preloads in lateral subqueries

---

lib/dataloader/ecto.ex

This fixes the specific issue I was having in #105 (preloads not using the same database prefix as the records being preloaded from), but I don't think it will be a complete solution - there are a few other calls to `repo.all` in the file that will probably have the same problem. 
I'm not sure what the best approach to fixing them all in an idiomatic way would be.

Use the same database prefix as the existing rows when preloading via a lateral join

---

lib/dataloader/ecto.ex

The Ecto "Basic Usage" example calls `Dataloader.get/4` which is only useful for getting single records, but  `Dataloader.get_many/4` is the correct function for fetching multiple records. This PR updates the example accordingly.

Fix function call in Ecto basic usage example

---

.formatter.exs
.gitignore
README.md
mix.exs

Besides other changes, this commit ensures the generated HTML doc for
HexDocs.pm will become the main source doc for this Elixir library which
leverage on ExDoc features.
List of changes:
* Update gitignore
* Update formatter config
* Use common source url
* Set readme as main doc
* Badges and more badges!
Screenshot:

Misc doc changes

---

lib/dataloader/ecto.ex
priv/test_repo/migrations/1_migrate_all.exs
test/dataloader/ecto/belongs_to_test.exs
test/dataloader/ecto/has_many_through_many_to_many_test.exs
test/dataloader/ecto/has_many_where_test.exs
test/dataloader/ecto/many_to_many_join_where_test.exs
test/dataloader/ecto/many_to_many_where_test.exs
test/support/leaderboard.ex
test/support/like.ex
test/support/picture.ex
test/support/post.ex
test/support/user.ex
test/support/user_picture.ex

We're using dataloader with a schema that has `where` and `join_where` clauses in many-to-many relationships.
Before this, these clauses where ignored.

Add support for where and join_where in many_to_many and has_many associations

---

README.md

Use different markdown so the extra comma will not append to the URL.

Fix broken link to fb dataloader in README

---

config/test.exs
lib/dataloader/ecto.ex
test/dataloader/ecto_test.exs

I believe this fixes https://github.com/absinthe-graphql/dataloader/issues/78

#78 order by of a has many through not respected

---

lib/dataloader.ex
lib/dataloader/ecto.ex
lib/dataloader/kv.ex
lib/dataloader/source.ex
test/dataloader/ecto_test.exs
test/dataloader_test.exs

In order to make dataloaders easier to use in test, I've added an `async?/1` function to the souurce protocol. In `async_safely/3` (which is now `async_safely/4`) we default to `async?: true` meaning this should be backwards compatible with any direct usage of that function. 
I've also added what would seem to me to be the proper default behavior for ecto and KV, which is that ecto will run synchronously if the repo is in a transaction, and KV is configurable at startup.
Feel free to tear it apart. This does seem pretty necessary for writing tests against absinthe in general, though :)
This is slightly orthoganal to #134 because its per-source
Addresses some if not all of #129

improvement: add async?/1 to source protocol

---

lib/dataloader/kv.ex
test/dataloader/ecto_test.exs
test/dataloader/kv_test.exs

These are the same telemetry events as for the Ecto source.

Adds batch telemetry event on the KV source

---

lib/dataloader.ex

Moduledocs automatically render links as HTML links and the comma was being tacked on, causing hexdocs to link to a broken url.
Thanks!

Fixes rendering issue where comma is included with FB dataloader link

---

lib/dataloader/ecto.ex

Since 3.10.0, Ecto warns when joining without `:on`:
> missing `:on` in join, defaulting to `on: true`.

Fix join warning using Ecto 3.10.0+
